# Generated by Django 3.1.7 on 2021-05-05 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0003_auto_20210501_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(verbose_name='First name')),
                ('last_name', models.TextField(verbose_name='Last name')),
                ('phone_number', models.TextField(verbose_name='Phone number')),
                ('email', models.TextField(verbose_name='E-mail')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.profile', verbose_name='Profile')),
            ],
        ),
    ]
