# Generated by Django 3.1.7 on 2021-05-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0004_characterdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterdata',
            options={'verbose_name': 'User data', 'verbose_name_plural': 'Users Data'},
        ),
        migrations.AddField(
            model_name='profile',
            name='statement',
            field=models.BooleanField(default=False, verbose_name='Form process status'),
        ),
    ]
